# Generated by Django 5.0.14 on 2026-08-29 17:25

import django.core.validators
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInstructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        upload_to="payment_qr/", verbose_name="QR-код для перевода"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Например: банк, получатель, номер счёта — что покупатель увидит рядом с QR",
                        verbose_name="Реквизиты / пояснение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Реквизиты для оплаты",
                "verbose_name_plural": "Реквизиты для оплаты",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Решение модератора"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество билетов"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=tickets.models.receipt_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "heic", "pdf", "webp"]
                    )
                ],
                verbose_name="Чек об оплате",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rejection_email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Письмо об аннулировании отправлено"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Чек загружен"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Telegram chat ID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="telegram_message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram message ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Письмо с билетом отправлено"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Оплачен (FreedomPay)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты (FreedomPay)"),
                    ("paid", "Оплачен (FreedomPay)"),
                    ("failed", "Не оплачен / отменён (FreedomPay)"),
                    ("awaiting_receipt", "Ожидает чек оплаты"),
                    ("pending_review", "Билет выдан, ждёт проверки модератором"),
                    ("approved", "Подтверждён модератором"),
                    ("rejected", "Отклонён, билет аннулирован"),
                ],
                default="awaiting_receipt",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
