# Generated by Django 5.0.14 on 2026-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0002_paymentinstructions_order_decided_at_order_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("manual", "Ручной перевод"),
                    ("freedompay", "FreedomPay"),
                    ("finik", "Finik"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Оплачен (через шлюз)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID платежа у платёжного шлюза"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Не оплачен / отменён"),
                    ("awaiting_receipt", "Ожидает чек оплаты"),
                    ("pending_review", "Билет выдан, ждёт проверки модератором"),
                    ("approved", "Подтверждён модератором"),
                    ("rejected", "Отклонён, билет аннулирован"),
                ],
                default="awaiting_receipt",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
