# Generated by Django 5.0.14 on 2026-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_order_payment_method_alter_order_paid_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_method",
                    models.CharField(
                        choices=[
                            ("manual", "Ручной перевод"),
                            ("freedompay", "FreedomPay"),
                            ("finik", "Finik"),
                        ],
                        default="finik",
                        help_text="Каким способом оплачивается билет при нажатии «Купить билет» на сайте. FreedomPay/Finik используют тестовый режим, пока не заданы реальные ключи в .env (см. FREEDOMPAY_TEST_MODE / FINIK_TEST_MODE).",
                        max_length=16,
                        verbose_name="Активный способ оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки оплаты",
                "verbose_name_plural": "Настройки оплаты",
            },
        ),
    ]
