# Generated by Django 5.0.14 on 2026-09-07 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_paymentsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="checked_in_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="qr_image",
        ),
        migrations.AlterField(
            model_name="order",
            name="qr_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Токен заказа",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="QR-токен",
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/",
                        verbose_name="QR-код",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отмечен на входе"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Билет",
                "verbose_name_plural": "Билеты",
                "ordering": ["order", "id"],
            },
        ),
    ]
