# Generated by Django 5.0.14 on 2026-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_remove_order_checked_in_at_remove_order_qr_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_legacy_shared_qr",
            field=models.BooleanField(
                default=False,
                help_text="Билет был выдан до введения отдельного QR на каждого человека — сканирование единственного QR допускает сразу всю группу (order.quantity), а не одного человека.",
                verbose_name="Старый заказ с общим QR на группу",
            ),
        ),
    ]
